# Generated by Django 2.1.7 on 2019-03-21 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DweetComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dweeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dweet', models.TextField(blank=True, null=True)),
                ('dweeter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwitterapp.Dweeter')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='dwitterapp.Dweeter')),
            ],
        ),
        migrations.AddField(
            model_name='dweetcomments',
            name='dweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwitterapp.Dweets'),
        ),
        migrations.AddField(
            model_name='dweetcomments',
            name='dweeter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwitterapp.Dweeter'),
        ),
    ]
