# Generated by Django 2.1.7 on 2019-03-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitterapp', '0002_auto_20190321_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dweeter',
            old_name='follower',
            new_name='follows',
        ),
    ]
