# Generated by Django 2.1.7 on 2019-03-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitterapp', '0003_auto_20190321_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweeter',
            name='follows',
            field=models.ManyToManyField(blank=True, null=True, related_name='_dweeter_follows_+', to='dwitterapp.Dweeter'),
        ),
    ]
