# Generated by Django 2.1.7 on 2019-03-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitterapp', '0004_auto_20190322_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweeter',
            name='follows',
            field=models.ManyToManyField(blank=True, db_column='from_dweeter_id', null=True, related_name='_dweeter_follows_+', to='dwitterapp.Dweeter'),
        ),
    ]
