# Generated by Django 2.1.7 on 2019-03-22 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwitterapp', '0006_auto_20190322_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='DweeterRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='dweeter',
            name='follows',
            field=models.ManyToManyField(through='dwitterapp.DweeterRelationship', to='dwitterapp.Dweeter'),
        ),
        migrations.AddField(
            model_name='dweeterrelationship',
            name='from_dweeter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_dweeter', to='dwitterapp.Dweeter'),
        ),
        migrations.AddField(
            model_name='dweeterrelationship',
            name='to_dweeter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_dweeter', to='dwitterapp.Dweeter'),
        ),
        migrations.AlterUniqueTogether(
            name='dweeterrelationship',
            unique_together={('from_dweeter', 'to_dweeter')},
        ),
    ]
